// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RensaioBackend.Data;

#nullable disable

namespace RensaioBackend.Migrations.Contribution
{
    [DbContext(typeof(ContributionDbContext))]
    partial class ContributionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.ContributionMetadataEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("LinkedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MappingId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("MappingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MappingId")
                        .HasDatabaseName("IX_Metadata_MappingId");

                    b.HasIndex("MappingStatus")
                        .HasDatabaseName("IX_Metadata_MappingType");

                    b.HasIndex("ProviderId", "ProviderKey")
                        .HasDatabaseName("IX_Metadata_ProviderId_ProviderKey");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.ContributionSeriesEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .HasColumnType("BLOB");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<byte[]>("MappingId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SourceId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MappingId")
                        .HasDatabaseName("IX_Sources_MappingId");

                    b.HasIndex("SourceId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.ContributionSourceEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("LastBatchExecutionUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<long>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Package", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sources_Package_SourceId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.MappingEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Mappings");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.MappingTitleEntity", b =>
                {
                    b.Property<byte[]>("MappingId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TitleId")
                        .HasColumnType("BLOB");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("MappingId", "TitleId");

                    b.HasIndex("TitleId");

                    b.ToTable("MappingTitles");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.SyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastServerVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.TitleEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.ContributionMetadataEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.ContributionDatabase.MappingEntity", "Mapping")
                        .WithMany()
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.ContributionSeriesEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.ContributionDatabase.MappingEntity", "Mapping")
                        .WithMany()
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RensaioBackend.Models.ContributionDatabase.ContributionSourceEntity", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("RensaioBackend.Models.ContributionDatabase.MappingTitleEntity", b =>
                {
                    b.HasOne("RensaioBackend.Models.ContributionDatabase.MappingEntity", "Mapping")
                        .WithMany()
                        .HasForeignKey("MappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RensaioBackend.Models.ContributionDatabase.TitleEntity", "Title")
                        .WithMany()
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mapping");

                    b.Navigation("Title");
                });
#pragma warning restore 612, 618
        }
    }
}
